linters:
  enable:
    # We opt-in to style linters without the preset since many
    # are too strict (e.g., no init functions allowed).
    - decorder
    - dupword
    - gci
    - gocritic
    - gofumpt
    - goprintffuncname
    - inamedparam
    - mirror
    - revive
    - stylecheck
    - tenv
    - unconvert
    - usestdlibvars
    - wastedassign
  presets:
    - bugs
    - performance

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/wasilibs/go-sql-formatter)
  gosec:
    config:
      G306: "0644"

issues:
  exclude:
    - don't use an underscore in package name
    - should not use underscores in package names
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - errchkjson
        - gosec
        - noctx
