name: "Update Upstream"

on:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write

jobs:
  build:
    uses: wasilibs/actions/.github/workflows/update-node.yaml@3a74924c1d1fdcf313557c374a13a102a4614a25
    with:
      packages: sql-formatter
    secrets: inherit
